from digimon_card_game.cards.information import DigimonType
from .assertions import assert_expected_enum_values


def test_01_digimon_types():
    assert_expected_enum_values(DigimonType, {"9000",
                                              "AA Defense Agent",
                                              "Ability Synthesis Agent",
                                              "Abnormal",
                                              "Alien",
                                              "Alien Humanoid",
                                              "Amphibian",
                                              "Ancient",
                                              "Ancient Animal",
                                              "Ancient Aquabeast",
                                              "Ancient Bird",
                                              "Ancient Birdkin",
                                              "Ancient Crustacean",
                                              "Ancient Dragon",
                                              "Ancient Dragonkin",
                                              "Ancient Fish",
                                              "Ancient Holy Warrior",
                                              "Ancient Insectoid",
                                              "Ancient Mineral",
                                              "Ancient Mutant",
                                              "Ancient Mythical Beast",
                                              "Ancient Plant",
                                              "Angel",
                                              "Ankylosaur",
                                              "Aquabeast",
                                              "Aquatic",
                                              "Archangel",
                                              "Armor",
                                              "Authority",
                                              "Avian",
                                              "Baby Dragon",
                                              "Bagra Army",
                                              "Base Defense Agent",
                                              "Beast",
                                              "Beast Dragon",
                                              "Beast Knight",
                                              "Beastkin",
                                              "Big Death-Stars",
                                              "Bird",
                                              "Bird Dragon",
                                              "Birdkin",
                                              "Blue Flare",
                                              "Boss",
                                              "Bulb",
                                              "Carnivorous Plant",
                                              "Ceratopsian",
                                              "Cherub",
                                              "Commander Agent",
                                              "Composite",
                                              "CRT",
                                              "Crustacean",
                                              "Cyborg",
                                              "D-Brigade",
                                              "Dark Animal",
                                              "Dark Dragon",
                                              "Dark Knight",
                                              "Demon",
                                              "Demon Lord",
                                              "Deva",
                                              "DigiPolice",
                                              "Dinosaur",
                                              "Dragon",
                                              "Dragon Warrior",
                                              "Dragonkin",
                                              "Earth Dragon",
                                              "Enhancement",
                                              "Espionage Agent",
                                              "Evil",
                                              "Evil Dragon",
                                              "Fairy",
                                              "Fallen Angel",
                                              "Fire Dragon",
                                              "Flame",
                                              "Food",
                                              "Four Great Dragons",
                                              "Four Sovereigns",
                                              "Galaxy",
                                              "General",
                                              "Ghost",
                                              "Giant Bird",
                                              "God Beast",
                                              "Grappling Agent",
                                              "Ground Combat Agent",
                                              "Holy Beast",
                                              "Holy Bird",
                                              "Holy Dragon",
                                              "Holy Sword",
                                              "Holy Warrior",
                                              "Hunter",
                                              "Ice-Snow",
                                              "Insectoid",
                                              "Intel Acquisition Agent",
                                              "Invader",
                                              "Larva",
                                              "LCD",
                                              "Legend-Arms",
                                              "Lesser",
                                              "Light Dragon",
                                              "Light Fang",
                                              "Machine",
                                              "Machine Dragon",
                                              "Magic Knight",
                                              "Magic Warrior",
                                              "Major",
                                              "Mammal",
                                              "Marine Man",
                                              "Mine",
                                              "Mineral",
                                              "Mini Angel",
                                              "Mini Bird",
                                              "Mini Dragon",
                                              "Minor",
                                              "Mollusk",
                                              "Monk",
                                              "Mothership Agent",
                                              "Musical Instrument",
                                              "Mutant",
                                              "Mysterious Beast",
                                              "Mysterious Bird",
                                              "Mythical Beast",
                                              "Mythical Dragon",
                                              "Night Claw",
                                              "NO DATA",
                                              "Olympos XII",
                                              "Parasite",
                                              "Perfect",
                                              "Plesiosaur",
                                              "Pterosaur",
                                              "Puppet",
                                              "Rare Animal",
                                              "Reconnaissance Agent",
                                              "Reptile",
                                              "Reptile Man",
                                              "Rock",
                                              "Rock Dragon",
                                              "Royal Knight",
                                              "Sea Animal",
                                              "Sea Beast",
                                              "Seraph",
                                              "Seven Great Demon Lords",
                                              "Shaman",
                                              "Sky Dragon",
                                              "SoC",
                                              "Stegosaur",
                                              "Subtypes",
                                              "Super Major",
                                              "Ten Warriors",
                                              "Three Great Angels",
                                              "Three Musketeers",
                                              "Throne",
                                              "Tropical Fish",
                                              "Twilight",
                                              "Unanalyzable",
                                              "Undead",
                                              "Unidentified",
                                              "Unique",
                                              "Unknown",
                                              "Vegetation",
                                              "Virtue",
                                              "Warrior",
                                              "Weapon",
                                              "Wizard",
                                              "X Antibody",
                                              "X Program",
                                              "Xros Heart"})
